/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThuVienRouteImport } from './routes/thu-vien'
import { Route as KhoaHocRouteImport } from './routes/khoa-hoc'
import { Route as HoiVienRouteImport } from './routes/hoi-vien'
import { Route as CuaHangRouteImport } from './routes/cua-hang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaiVietSlugRouteImport } from './routes/bai-viet.$slug'

const ThuVienRoute = ThuVienRouteImport.update({
  id: '/thu-vien',
  path: '/thu-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const KhoaHocRoute = KhoaHocRouteImport.update({
  id: '/khoa-hoc',
  path: '/khoa-hoc',
  getParentRoute: () => rootRouteImport,
} as any)
const HoiVienRoute = HoiVienRouteImport.update({
  id: '/hoi-vien',
  path: '/hoi-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const CuaHangRoute = CuaHangRouteImport.update({
  id: '/cua-hang',
  path: '/cua-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaiVietSlugRoute = BaiVietSlugRouteImport.update({
  id: '/bai-viet/$slug',
  path: '/bai-viet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cua-hang': typeof CuaHangRoute
  '/hoi-vien': typeof HoiVienRoute
  '/khoa-hoc': typeof KhoaHocRoute
  '/thu-vien': typeof ThuVienRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cua-hang': typeof CuaHangRoute
  '/hoi-vien': typeof HoiVienRoute
  '/khoa-hoc': typeof KhoaHocRoute
  '/thu-vien': typeof ThuVienRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cua-hang': typeof CuaHangRoute
  '/hoi-vien': typeof HoiVienRoute
  '/khoa-hoc': typeof KhoaHocRoute
  '/thu-vien': typeof ThuVienRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cua-hang'
    | '/hoi-vien'
    | '/khoa-hoc'
    | '/thu-vien'
    | '/bai-viet/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cua-hang'
    | '/hoi-vien'
    | '/khoa-hoc'
    | '/thu-vien'
    | '/bai-viet/$slug'
  id:
    | '__root__'
    | '/'
    | '/cua-hang'
    | '/hoi-vien'
    | '/khoa-hoc'
    | '/thu-vien'
    | '/bai-viet/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuaHangRoute: typeof CuaHangRoute
  HoiVienRoute: typeof HoiVienRoute
  KhoaHocRoute: typeof KhoaHocRoute
  ThuVienRoute: typeof ThuVienRoute
  BaiVietSlugRoute: typeof BaiVietSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thu-vien': {
      id: '/thu-vien'
      path: '/thu-vien'
      fullPath: '/thu-vien'
      preLoaderRoute: typeof ThuVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khoa-hoc': {
      id: '/khoa-hoc'
      path: '/khoa-hoc'
      fullPath: '/khoa-hoc'
      preLoaderRoute: typeof KhoaHocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoi-vien': {
      id: '/hoi-vien'
      path: '/hoi-vien'
      fullPath: '/hoi-vien'
      preLoaderRoute: typeof HoiVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cua-hang': {
      id: '/cua-hang'
      path: '/cua-hang'
      fullPath: '/cua-hang'
      preLoaderRoute: typeof CuaHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bai-viet/$slug': {
      id: '/bai-viet/$slug'
      path: '/bai-viet/$slug'
      fullPath: '/bai-viet/$slug'
      preLoaderRoute: typeof BaiVietSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuaHangRoute: CuaHangRoute,
  HoiVienRoute: HoiVienRoute,
  KhoaHocRoute: KhoaHocRoute,
  ThuVienRoute: ThuVienRoute,
  BaiVietSlugRoute: BaiVietSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
